#!/bin/bash
if [ ! -e pywikibot ]
then
  svn co http://svn.wikimedia.org/svnroot/pywikipedia/branches/rewrite/pywikibot
fi
PYWIKIBOT2_DIR=$PWD
ssh -i id_rsa -p 29418 reviewer-bot@gerrit.wikimedia.org  gerrit stream-events | python add_reviewer.py
