#!/bin/bash
if [ ! -e pywikibot ]
then
  git clone https://gerrit.wikimedia.org/r/pywikibot/core pywikibot
  (cd pywikibot && git checkout 2.0)
fi
if [ ! -e python-gerrit ]
then
  git clone https://github.com/valhallasw/python-gerrit.git #https://github.com/bcwaldon/python-gerrit.git
  cd python-gerrit; git checkout remotes/origin/rpcurls; cd ..      
fi

export PYWIKIBOT2_DIR=$PWD
ssh -i id_rsa -p 29418 reviewer-bot@gerrit.wikimedia.org  gerrit stream-events | python add_reviewer.py
