#!/bin/bash
cd $HOME/src/gerrit-reviewer-bot/src/
git pull
if [ ! -e pywikibot ]
then
  git clone https://gerrit.wikimedia.org/r/pywikibot/core pywikibot
  (cd pywikibot && git checkout 2.0)
fi

export PYWIKIBOT2_DIR=$PWD
while /bin/true
do
	echo ===== STARTING RUN AT `date`
	../bin/python pop3bot.py
	echo ===== RUN ENDED AT `date`
        echo
	sleep 300
done
